/* Example program to calculate a grid of points for a Gastner-Newman
 * cartogram using the cartogram.c code
 *
 * Written by Mark Newman
 *
 * See http://www.umich.edu/~mejn/ for further details.
 */


#include <stdio.h>
#include <stdlib.h>
#include <teem/meet.h>

#include "ocart.h"


/* The parameter OFFSET specifies a small amount to be added the density in
 * every grid square, as a Fraction of the mean density on the whole
 * lattice.  This prevents negative densities from being generated by
 * numerical errors in the FFTs which can cause problems for the
 * integrator.  If the program is giving weird behavior, particularly at
 * the beginning of a calculation, try increasing this quantity by a factor
 * of 10.
 */

#define OFFSET 0.005


/* Function to read population data into the array rho.  Returns 1 if there
 * was a problem, zero otherwise */

int readpop(FILE *stream, double **rho, int xsize, int ysize)
{
  int ix,iy;
  int n;
  double mean;
  double sum=0.0;

  for (iy=0; iy<ysize; iy++) {
    for (ix=0; ix<xsize; ix++) {
      n = fscanf(stream,"%lf",&rho[ix][iy]);
      if (n!=1) return 1;
      sum += rho[ix][iy];
    }
  }

  mean = sum/(xsize*ysize);
  for (iy=0; iy<ysize; iy++) {
    for (ix=0; ix<xsize; ix++) {
      rho[ix][iy] += OFFSET*mean;
    }
  }

  return 0;
}


/* Function to make the grid of points */

void creategrid(double *gridx, double *gridy, int xsize, int ysize)
{
  int ix,iy;
  int i=0;

  for (iy=0; iy<=ysize; iy++) {
    for (ix=0; ix<=xsize; ix++) {
      gridx[i] = ix;
      gridy[i] = iy;
      i++;
    }
  }
}


static const char *cartInfo =
  ("very lightly Teem-fied cart, "
   "based on http://www-personal.umich.edu/~mejn/cart/.");

int
main(int argc, const char *argv[])
{
  int xsize,ysize;
  double *gridx,*gridy;  // Array for grid points
  double **rho;          // Initial population density
  FILE *infp;

  const char *me = argv[0];
  airArray *mop = airMopNew();
  hestParm *hparm = hestParmNew();
  hestOpt *hopt = NULL;
  char *err, *inName, *outName, *rgName;
  airMopAdd(mop, hparm, AIR_CAST(airMopper, hestParmFree), airMopAlways);
  hestOptAdd(&hopt, NULL, "xsize", airTypeInt, 1, 1, &xsize, NULL,
             "xsize");
  hestOptAdd(&hopt, NULL, "ysize", airTypeInt, 1, 1, &ysize, NULL,
             "ysize");
  hestOptAdd(&hopt, NULL, "inputfile", airTypeString, 1, 1, &inName, NULL,
             "input filename");
  hestOptAdd(&hopt, NULL, "outputfile", airTypeString, 1, 1, &outName, NULL,
             "output filename; should end with .nrrd");
  hestOptAdd(&hopt, "g", "gridfile", airTypeString, 1, 1, &rgName, "",
             "if given a filename with this option, the reference grid "
             "(with no displacement from the cartogram) is saved here, "
             "to simplify inspection of cartogram results. ");
  hestParseOrDie(hopt, argc-1, argv+1, hparm,
                 me, cartInfo, AIR_TRUE, AIR_TRUE, AIR_TRUE);
  airMopAdd(mop, hopt, AIR_CAST(airMopper, hestOptFree), airMopAlways);
  airMopAdd(mop, hopt, AIR_CAST(airMopper, hestParseFree), airMopAlways);

  infp = fopen(inName,"r");
  if (infp==NULL) {
    fprintf(stderr,"%s: unable to open file \"%s\"\n", me, inName);
    airMopError(mop);
    exit(4);
  }
  airMopAdd(mop, infp, (airMopper)airFclose, airMopAlways);

  /* Allocate space for the cartogram code to use */

  cartContext *ctx = cartContextNew();
  airMopAdd(mop, ctx, (airMopper)cartContextNix, airMopAlways);
  cart_makews(ctx, xsize,ysize);
  fprintf(stderr, "%s: x,y size = %d %d\n", me, xsize, ysize);

  /* Read in the population data, transform it, then destroy it again */
  rho = cart_dmalloc(xsize,ysize);
  if (readpop(infp,rho,xsize,ysize)) {
    fprintf(stderr, "%s: density file contains too few or incorrect data\n", me);
    airMopError(mop);
    exit(6);
  }
  cart_transform(ctx,rho,xsize,ysize);
  cart_dfree(rho);

  /* Create the grid of points */
  Nrrd *ngridx = nrrdNew();
  airMopAdd(mop, ngridx, (airMopper)nrrdNuke, airMopAlways);
  Nrrd *ngridy = nrrdNew();
  airMopAdd(mop, ngridy, (airMopper)nrrdNuke, airMopAlways);
  size_t gsize[2] = {xsize+1, ysize+1};
  if (nrrdMaybeAlloc_nva(ngridx, nrrdTypeDouble, 2, gsize) ||
      nrrdMaybeAlloc_nva(ngridy, nrrdTypeDouble, 2, gsize)) {
    airMopAdd(mop, err = biffGetDone(NRRD), airFree, airMopAlways);
    fprintf(stderr, "%s: problem allocating grid: %s", me, err);
    airMopError(mop);
    exit(7);
  }
  gridx = (double*)(ngridx->data);
  gridy = (double*)(ngridy->data);
  creategrid(gridx,gridy,xsize,ysize);
  Nrrd *ngrid = nrrdNew();
  airMopAdd(mop, ngrid, (airMopper)nrrdNuke, airMopAlways);
  const Nrrd *njoin[2] = {ngridx, ngridy};
  if (strlen(rgName)) {
    if (nrrdJoin(ngrid, njoin, 2, 0, AIR_TRUE) ||
        nrrdSave(rgName, ngrid, NULL)) {
      airMopAdd(mop, err = biffGetDone(NRRD), airFree, airMopAlways);
      fprintf(stderr, "%s: problem creating or saving reference grid: %s", me, err);
      airMopError(mop);
      exit(8);
    }
  }

  /* Make the cartogram */
  double time0 = airTime();
  cart_makecart(ctx,gridx,gridy,(xsize+1)*(ysize+1),xsize,ysize,0.0);
  double time1 = airTime();
  printf("%s:              ... %g secs\n", me, time1-time0);

  if (nrrdJoin(ngrid, njoin, 2, 0, AIR_TRUE) ||
      nrrdSave(outName, ngrid, NULL)) {
    airMopAdd(mop, err = biffGetDone(NRRD), airFree, airMopAlways);
    fprintf(stderr, "%s: problem creating or saving output grid: %s", me, err);
    airMopError(mop);
    exit(9);
  }

  /* Free up the allocated space */
  cart_freews(ctx,xsize,ysize);

  airMopOkay(mop);
  return 0;
}
