/* Example program to calculate a grid of points for a Gastner-Newman
 * cartogram using the cartogram.c code
 *
 * Written by Mark Newman
 *
 * See http://www.umich.edu/~mejn/ for further details.
 */


#include <stdio.h>
#include <stdlib.h>

#include <teem/meet.h>
#include "cart.h"


/* The parameter OFFSET specifies a small amount to be added the density in
 * every grid square, as a Fraction of the mean density on the whole
 * lattice.  This prevents negative densities from being generated by
 * numerical errors in the FFTs which can cause problems for the
 * integrator.  If the program is giving weird behavior, particularly at
 * the beginning of a calculation, try increasing this quantity by a factor
 * of 10.
 */

#define OFFSET 0.005


/* Function to read population data into the array rho.  Returns 1 if there
 * was a problem, zero otherwise */
/* GLK: Actually, ha ha no, now its just about adding OFFSET*mean */
int readpop(/* FILE *stream, double **rho */ double *rho, int xsize, int ysize)
{
  int ii;
  int n;
  double mean;
  double sum=0.0;

  /*
    NOTE that reading values from stream, X is the faster axis,
    but when stored in memory, X is the slower axis!
  for (iy=0; iy<ysize; iy++) {
    for (ix=0; ix<xsize; ix++) {
      n = fscanf(stream,"%lf",&rho[ix][iy]);
      if (n!=1) return 1;
      sum += rho[ix][iy];
    }
  }
  */

  for (ii=0; ii<xsize*ysize; ii++) {
    sum += rho[ii];
  }
  mean = sum/(xsize*ysize);
  for (ii=0; ii<xsize*ysize; ii++) {
    rho[ii] += OFFSET*mean;
  }

  return 0;
}


/* Function to make the grid of points */

void creategrid(double *gridx, double *gridy, int xsize, int ysize)
{
  int ix,iy;
  int i;

  for (ix=0; ix<=xsize; ix++) {
    for (iy=0,i=0; iy<=ysize; iy++) {
      gridx[i] = ix;
      gridy[i] = iy;
      i++;
    }
  }
}


/* Function to write out the grid points */

void writepoints(FILE *stream, double *gridx, double *gridy, int npoints)
{
  int i;

  for (i=0; i<npoints; i++) fprintf(stream,"%g %g\n",gridx[i],gridy[i]);
}

static const char *cartInfo =
  ("heavily Teem-fied cart, "
   "based on http://www-personal.umich.edu/~mejn/cart/.");

int
main(int argc, const char *argv[]) {
  double *gridx,*gridy;  // Array for grid points
  FILE *outfp;
  cartContext *ctx;

  const char *me = argv[0];
  airArray *mop = airMopNew();
  hestParm *hparm = hestParmNew();
  hestOpt *hopt = NULL;
  Nrrd *nrho;
  char *outName;
  unsigned int repeats;
  airMopAdd(mop, hparm, AIR_CAST(airMopper, hestParmFree), airMopAlways);
  hestOptAdd(&hopt, "i", "rho", airTypeOther, 1, 1, &nrho, NULL,
             "input population data", NULL, NULL, nrrdHestNrrd);
  hestOptAdd(&hopt, "r", "repeats", airTypeUInt, 1, 1, &repeats, "1",
             "number of times to re-run the computation, just so "
             "that it takes longer and provides an easier target "
             "for profiling tools");
  hestOptAdd(&hopt, "o", "fname", airTypeString, 1, 1, &outName, NULL,
             "output filename");
  hestParseOrDie(hopt, argc-1, argv+1, hparm,
                 me, cartInfo, AIR_TRUE, AIR_TRUE, AIR_TRUE);
  airMopAdd(mop, hopt, AIR_CAST(airMopper, hestOptFree), airMopAlways);
  airMopAdd(mop, hopt, AIR_CAST(airMopper, hestParseFree), airMopAlways);

  if (!( 2 == nrho->dim && nrrdTypeDouble == nrho->type )) {
    fprintf(stderr, "%s: want 2-D array of doubles (not %u-D of %s)\n", me,
            nrho->dim, airEnumStr(nrrdType, nrho->type));
    airMopError(mop);
    return 1;
  }
  double *rho = (double*)nrho->data;
  int xsize = (int)nrho->axis[1].size;
  int ysize = (int)nrho->axis[0].size;

  ctx = cartContextNew();
  airMopAdd(mop, ctx, (airMopper)cartContextNix, airMopAlways);

  /* Allocate space for the cartogram code to use */
  cart_makews(ctx,xsize,ysize);

  /* add OFFSET*mean */
  readpop(rho,xsize,ysize);
  cart_forward(ctx,rho,xsize,ysize);

  /* Create the grid of points */

  gridx = malloc((xsize+1)*(ysize+1)*sizeof(double));
  gridy = malloc((xsize+1)*(ysize+1)*sizeof(double));

  /* Make the cartogram */
  unsigned int repIdx;
  for (repIdx=0; repIdx<repeats; repIdx++) {
    if (repeats > 1) {
      printf("%s: repeat %u/%u\n", me, repIdx, repeats);
    }
    creategrid(gridx,gridy,xsize,ysize);
    cart_makecart(ctx,gridx,gridy,(xsize+1)*(ysize+1),xsize,ysize,0.0);
  }

  /* Write out the final positions of the grid points */
  if (!( outfp = fopen(outName, "w") )) {
    fprintf(stderr, "%s: couldn't open %s for writing\n", me, outName);
    airMopError(mop);
    return 1;
  }
  airMopAdd(mop, outfp, (airMopper)airFclose, airMopAlways);
  writepoints(outfp,gridx,gridy,(xsize+1)*(ysize+1));

  /* Free up the allocated space */
  cart_freews(ctx,xsize,ysize);
  free(gridx);
  free(gridy);

  /* cleanup */
  airMopOkay(mop);
  return 0;
}
